### ISSUE TITLE
Morning session issue 1/5/2023

### ISSUE THREAD

**Issue by zewdu444** [Sammy3000/PC-Africa#2]
## Morning session issue 1/5/2023 on readme file

- [x] It would be preferable to provide screenshots for the desktop and mobile versions as they are absent from your readme file.
- [x] It would be perfect to  remove double quote from image array values

**Comment by Sammy3000** [comment]
@zewdu444 . Thank you for the feedback 👍 . All issues have been sorted cheers 😃
